### PR TITLE
add new references

### PR DESCRIPTION
**Pull request by rvalieris**
added references and some small fixes

* new dir reference_and_annotation with the VDJ pieces used
* added scaleFactors_from_spikeSummary.R from another repo, for spike normalization factors

### CODE REVIEW

**Review by fruce-ki — CHANGES_REQUESTED** [review]
(1)
reference_and_annotation/ReadMe.txt

This description doesn't match the contents of the directory added to the repo.  this needs to be updated or removed.


(2)
If we are going to include references in the PRO repo as well as the MutPE repo, then we might as well include the other references here too, not just the new ones' for completeness. Otherwise it will be confusing.

**Comment by rvalieris** [comment]
I updated the readme.

I though we could include just the files necessary for PROcap here, there is an overlap with Mutpe but its not quite the same since Procap doesn't need the bed files from Mutpe.

**Comment by fruce-ki** [comment]
It is ok to include just the relevant references. My point was that it has to also include any of my references that are relevant as well, which currently are only available through the references collection in the MutPE repo (and those are probably not all relevant for the final paper).

**Comment by rvalieris** [comment]
I see ! ok, I added B18hi_all and CH12_VDJ_200122 from the MutPE repo, I think thats all ?

**Review by fruce-ki — APPROVED** [review]

**Pull request merged**
